added read_write_server to ci

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -45,3 +45,17 @@ jobs:
               echo "make job failed"
               exit $status
           fi
+
+    - name: Run Read-Write Server
+      run: |
+          cd examples/read_write_server
+          make install
+          make node &
+          sleep 1
+          
+          timeout 6s make job || echo "make job terminated after timeout"
+          status=$?
+          if [ $status -ne 0 ] && [ $status -ne 124 ]; then
+              echo "make job failed"
+              exit $status
+          fi
