fixed codegen

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -31,3 +31,18 @@ jobs:
 
     - name: Check formatting
       run: cargo fmt --all -- --check
+
+    - name: Run Ping Pong
+      run: |
+          make install_node
+          make install_jobc
+          make build_ops
+          make node &
+          sleep 1
+          
+          timeout 6s make job || echo "make job terminated after timeout"
+          status=$?
+          if [ $status -ne 0 ] && [ $status -ne 124 ]; then
+              echo "make job failed"
+              exit $status
+          fi
